const types = {
    SAVE_ALL_COUNTRIES: "SAVE_ALL_COUNTRIES",
    FILTER_COUNTRIES:"FILTER_COUNTRIES",
    ANCHOR_NEW_COUNTRY: "ANCHOR_NEW_COUNTRY",
    DELETE_FROM_ANCHOR_COUNTRY: "DELETE_FROM_ANCHOR_COUNTRY",
    DELETE_FROM_ALL_COUNTRY: "DELETE_FROM_ALL_COUNTRY"
}

export default types